In [2]:
from numpy import *
arr=linspace(0,16,10)
arr

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [3]:
arr=arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [6]:
arr=arange(10,0,-2)
print(arr)

[10  8  6  4  2]


In [7]:
arr=logspace(1,40,5)
arr

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [8]:
arr=zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
arr=ones(10,int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
i=0
while i<len(arr):
    arr[i]+=5
    i+=1

In [13]:
arr

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [14]:
arr+=5
arr

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [19]:
from numpy import *
print(sqrt(arr))

[3.31662479 3.31662479 3.31662479 3.31662479 3.31662479 3.31662479
 3.31662479 3.31662479 3.31662479 3.31662479]


In [21]:
arr=array([1,2,3,4,665,-2])

In [26]:
print(sort(arr))

[ -2   1   2   3   4 665]


In [3]:
from numpy import *
a=array([1,2,3])
b=array([4,5,6])
print(concatenate([a,b]))

[1 2 3 4 5 6]


In [7]:
a=array([2,5,6,4,7])
b=a
print(a)
print(b)
a=array([1,1,1,1])
print(a)
print(b)



[2 5 6 4 7]
[2 5 6 4 7]
[1 1 1 1]
[2 5 6 4 7]


In [29]:
from numpy import *
a=array([1,2])
a.append([3])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
print(id(a))
print(id(c))
print(a)
print(c)

78671128
78730568
[1 1 1 1]
[1 1 1 1]


In [12]:
print(a)

[1 1 1 1]


In [16]:
a=array([1,3,5,7])
b=a.copy()
a[1]=88
print(a)
print(b)


[ 1 88  5  7]
[1 3 5 7]


In [33]:
from array import *
a=array('i',[1,2,-3,-4])
b=array('i',[-10,-12,55,8])
d=array('i',[])
k=0
for n in a:
    d.append(n+b[k])
    k+=1

    

In [34]:
print(d)

array('i', [-9, -10, 52, 4])


In [32]:
from array import *
n=int(input("Please input number of elemenst"))
a=array('i',[])
i=0
while i<n:
    a.append(int(input('Put your value')))
    i+=1
print(a)

num=0
i=0
while i<n:
    j=i+1
    while j<n:
        if a[i]<a[j]:
            num=a[i]
            a[i]=a[j]
            a[j]=num
        j+=1
    i+=1
print('Descending order of the array is',a)
print('Max value is ',a[0])
    

Please input number of elemenst5
Put your value1
Put your value8
Put your value7
Put your value6
Put your value9
array('i', [1, 8, 7, 6, 9])
Descending order of the array is array('i', [9, 8, 7, 6, 1])
Max value is  9


In [2]:
from numpy import *
x=array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x.ndim

2

In [5]:
x.shape

(3, 3)

In [6]:
y=x.flatten()

In [7]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
z=y.reshape(3,3)

In [9]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
l=array([1,2,3,4,5,6,7,8])


In [18]:
a=l.reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
z=l.reshape(2,4)

In [21]:
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
m=matrix(z)

In [23]:
m

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [27]:
n=matrix('1 2 3 4 ; 5 6 7 8')

In [28]:
n

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [32]:
n=matrix('1 2 3;4 5 6;7 8 9')

In [33]:
print(diagonal(n))

[1 5 9]


In [36]:
m=matrix('1 2 ; 3 4')
n=matrix('5 6 ; 7 8')
print(m)
print(n)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [37]:
l=m*n
print(l)

[[19 22]
 [43 50]]


In [7]:
def add():
    a=int(input('Put your first number'))
    b=int(input('Put your second number'))
    print(a+b)
result=add()

Put your first number6
Put your second number6
12


In [5]:
result

10

In [12]:
def update(x):
    print(id(x))
    x=8
    print(id(x))
    print(x)
update(5)

266328352
266328400
8


In [13]:
a=55
print(id(a))
update(a)
print(a)

266329152
266329152
266328400
8
55


In [15]:
b=5
print(id(b))
print(b)
b=6
print(id(b))
print(b)

266328352
5
266328368
6


In [16]:
def upd(x):
    print(id(x))
    x[1]=100
    print(id(x))
a=[1,2,3]
print(id(a))
upd(a)
print(a)

61844736
61844736
61844736
[1, 100, 3]


In [19]:
def sub(a,b):
    return(a-b)
r=sub(b=6,a=5)
print(r)

-1


In [23]:
def person(name,age=18):
    print(name)
    print(age)
person('Rounak',28)

Rounak
28


In [31]:
def s(*b):
    c=0
    for i in b:
        c+=i
    print(c)
s(1,2,3,4,5,6,7,8,9,10)

55


In [52]:
def collection(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
collection('Rounak',age=18,city='Mumbai')

Rounak
age 18
city Mumbai


In [41]:
x={'name':'Rounak','age':18}

In [51]:
for i,j in x.items():
    print(i,j)

name Rounak
age 18


In [56]:
x

{'name': 'Rounak', 'age': 18}

In [63]:
a=10
print(id(a))

def met(a):
    a=145
    print(id(a))
    print(a)
met(15)
print(a)

266328432
266330592
145
10


In [65]:
a=10
def something():
    global a
    a=15
    print(id(a))
    print(a)

something()    
print(a)

print('outside',id(a))

266328512
15
15
outside 266328512


In [66]:
a

15

In [67]:
def nothing():
    global a
    a=15
    print(a)
    a=9
    print(a)
nothing()

15
9


In [68]:
a

9

In [71]:
def so():
    a=55.5
    x=globals()['a']=44
    
    print(a)
    print(x)
so()

55.5
44


In [72]:
a

44

In [79]:
x=[]
e=[]
o=[]
k=0
l=0
n=int(input('Insert number of numbers'))
i=0
while i<n:
    x.append(int(input('Enter the number')))
    i+=1
for i in x:
    if i%2==0:
        e.append(i)
        k+=1
    else:
        o.append(i)
        l+=1

print('Number of even numbers',k)
print('Number of odd numbers',l)
print('even numbers are',e)
print('odd numbers are ',o)


Insert number of numbers5
Enter the number1
Enter the number2
Enter the number3
Enter the number4
Enter the number5
Number of even numbers 2
Number of odd numbers 3
even numbers are [2, 4]
odd numbers are  [1, 3, 5]


In [90]:

def funx(x):
    k,l=0,0
    e=[]
    o=[]
    for i in x:
        if i%2==0:
            e.append(i)
            k+=1
        else:
            o.append(i)
            l+=1
        
    print('even numbers :{},odd numbers: {}'.format(e,o))

y=[1,3,5,7,9]
funx(x)



even numbers :[2, 4, 2, 4],odd numbers: [1, 3, 5, 1, 3, 5]


In [93]:
def name(x):
    m=0
    l=0
    more_than_5=[]
    less_than_5=[]
    for i in x:
        if len(i)>=5:
            m+=1
            more_than_5.append(i)
        else:
            l+=1
            less_than_5.append(i)
    print('Number of names having more than 5 letter:{},Number of names having less than 5 characters:{}'.format(m,l))
    print('More than 5:{},Less than 5:{}'.format(more_than_5,less_than_5))
names=[]
i=1
while i<=10:
    names.append(input("Please enter your name"))
    i+=1
name(names)

            
            
        
    

Please enter your nameRon
Please enter your nameGor
Please enter your nameMor
Please enter your nameYas
Please enter your nameJohn
Please enter your namePoonam
Please enter your nameVinod
Please enter your namekkkkkkkkkkkkkkk
Please enter your nameUUUUUUUUUUUU
Please enter your name1234567
Number of names having more than 5 letter:5,Number of names having less than 5 characters:5
More than 5:['Poonam', 'Vinod', 'kkkkkkkkkkkkkkk', 'UUUUUUUUUUUU', '1234567'],Less than 5:['Ron', 'Gor', 'Mor', 'Yas', 'John']


In [105]:
n=int(input('Number of terms'))
if n<0:
    print('Learn maths, bud')
else:
    def fib(n):
        i=0
        x=[]
        while i<n:
            if i<=1:
                x.append(i)
            else:
                x.append(x[i-1]+x[i-2])
            i+=1
        for i in x:
            print(i)
    fib(n)        

Number of terms5
0
1
1
2
3


In [115]:
n=5
def fact(n):
    
    fact=1
    for i in range(1,n+1,1):
        fact*=i
    print(fact)
fact(n)

120


In [123]:
def greet():
    print('Hello')
greet()

Hello


In [126]:
import sys
sys.setrecursionlimit(1000)
print(sys.getrecursionlimit())


1000


In [133]:
def factr(n):
    
    if n==0:
        return 1
    return n*factr(n-1)
factr(5)

120

In [135]:
f=lambda a:a*a
print(f(5))

25


In [141]:
def even(n):
    return n%2==0
nums=[1,2,3,4,5,6,7,8,99,9,8,9,7,8,7,6]
evens=list(filter(even,nums))

In [142]:
evens

[2, 4, 6, 8, 8, 8, 6]

In [145]:
nums=list(filter(lambda n:n%2==0,nums))
print(nums)

[2, 4, 6, 8, 8, 8, 6]


In [148]:
i=0
while i<len(nums):
    nums[i]+=2
    i+=1

In [149]:
nums

[4, 6, 8, 10, 10, 10, 8]

In [150]:
double=list(map(lambda n:n+2,nums))
print(double)

[6, 8, 10, 12, 12, 12, 10]


In [155]:
from functools import reduce
sums=reduce(lambda a,b:a+b,double)
print(sums)

70


In [163]:
def div(a,b):
    return a/b
def smart_div(fun):
    def rev(a,b):
        if a<b:
            a,b=b,a
        return(fun(a,b))
    return rev
div=smart_div(div)
div(100,2)
   
    
  

50.0

In [165]:
import numpy as np
def smart(fun):
    def inner(a):
        a+=5
        return(fun(a))
    return inner
np.sqrt=smart(np.sqrt)
np.sqrt(20)


5.0

In [168]:
pwd

'C:\\Users\\aish\\Desktop\\Python Data Science'

In [170]:
print(__name__)

__main__
